resource "fmc_certificate_enrollment" "example" {
  name                                            = "my_certificate_enrollment"
  description                                     = "My certificate enrollment"
  enrollment_type                                 = "SELF_SIGNED_CERTFICATE"
  validate_ipsec_client                           = true
  validate_ssl_server                             = true
  validate_ssl_client                             = true
  skip_ca_flag_check                              = false
  include_fqdn                                    = "NONE"
  include_device_ip                               = "10.10.10.1"
  common_name                                     = "ftd.example.com"
  organizational_unit                             = "my_organizational_unit"
  organization                                    = "my_organization"
  locality                                        = "my_locality"
  state                                           = "my_state"
  country_code                                    = "PL"
  email                                           = "me@example.com"
  include_device_serial_number                    = true
  key_type                                        = "RSA"
  key_name                                        = "my_key"
  key_size                                        = "CertKey_2048"
  ignore_ipsec_key_usage                          = false
  enable_certificate_revocation_list              = true
  use_crl_distribution_point_from_the_certificate = true
  enable_static_certificate_revocation_list       = true
  cert_revocation_static_url_list                 = ["http://example.com/crl.pem"]
  enable_online_certificate_status_protocol       = true
  online_certificate_status_protocol_url          = "http://example.com/ocsp"
  evaluation_priority                             = "CRL"
  ignore_revocation                               = false
}
