---
name: Application Type
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/object/applicationtypes
no_resource: true
no_import: true
doc_category: Objects
attributes:
  - model_name: name
    type: String
    description: >-
      Name of the Application Type.
    mandatory: true
    example: Webapp
    data_source_query: true
  - model_name: type
    type: String
    description: Type of the object; this value is always 'ApplicationType'.
    computed: true
