---
name: Application Types
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/object/applicationtypes
no_resource: true
no_import: true
is_bulk: true
doc_category: Objects
attributes:
  - model_name: items
    type: Map
    description: >-
      Map of Application Types. The key of the map is the name of the individual Application Type.
    map_key_example: Webapp
    mandatory: true
    attributes:
      - model_name: id
        type: String
        resource_id: true
        description: Id of the managed Application Type.
        exclude_example: true
        exclude_test: true        
      - model_name: type
        type: String
        description: Type of the object; this value is always 'ApplicationType'.
        computed: true
