---
name: Application Risk
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/object/applicationrisks
ds_description: This data source reads the Application Risk level.
no_resource: true
no_import: true
doc_category: Objects
attributes:
  - model_name: name
    type: String
    description: >-
      Name of the Application Risk level.
    mandatory: true
    example: Very High
    data_source_query: true
  - model_name: type
    type: String
    description: Type of the object; this value is always 'ApplicationRisk'.
    computed: true
