---
name: FTD Platform Settings ICMP Access
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/policy/ftdplatformsettingspolicies/%v/icmpsettings
doc_category: Devices
minimum_version: "7.7"
res_description: This resource manages FTD Platform Settings - ICMP Access.
put_create: true
retrieve_id: true
put_delete: true
skip_minimum_test: true
attributes:
  - tf_name: ftd_platform_settings_id
    type: String
    reference: true
    description: Id of the parent FTD Platform Settings.
    example: 76d24097-41c4-4558-a4d0-a8c07ac08470
    test_value: fmc_ftd_platform_settings.test.id
  - model_name: type
    type: String
    description: Type of the object; this value is always 'ICMPSetting'.
    computed: true
  - model_name: rateLimit
    type: Int64
    description: Rate limit on ICMPv4 Unreachable messages.
    min_int: 1
    max_int: 100
    default_value: 1
    example: 1
  - model_name: burstSize
    type: Int64
    description: Burst size on ICMPv4 Unreachable messages.
    min_int: 1
    max_int: 10
    default_value: 1
    example: 1
  - model_name: icmpConfigs
    tf_name: configurations
    type: List
    description: ICMP access rules.
    attributes:
      - model_name: icmpAction
        tf_name: action
        type: String
        description: Action to take on matching ICMP packets.
        enum_values: [Permit, Deny]
        mandatory: true
        example: Permit
      - model_name: id
        data_path: [icmpService]
        tf_name: icmp_service_id
        type: String
        description: ID of the ICMP Service object.
        mandatory: true
        id: true
        example: 5a9f2d3c-08d1-11e6-b939-00155d0a1eb1
        test_value: fmc_icmpv4_object.test.id
      - model_name: id
        data_path: [network, object]
        tf_name: source_network_object_id
        type: String
        description: Id of network object (host, network, network group) defining the source IP addresses for ICMP access.
        example: 5a9f6d9c-3f8d-11e4-9163-6c4008b8c5d7
        test_value: fmc_host.test.id
        mandatory: true
        id: true
      - model_name: literals
        data_path: [interfaces]
        tf_name: interface_literals
        type: Set
        element_type: String
        description: List of interface literals for this rule.
        exclude_example: true
        exclude_test: true
      - model_name: objects
        data_path: [interfaces]
        tf_name: interface_objects
        type: Set
        description: List of interface objects (Security Zones or Interface Groups) for this rule.
        attributes:
          - model_name: id
            type: String
            description: Id of the interface object.
            example: 123e4567-e89b-12d3-a456-426614174000
            mandatory: true
            test_value: fmc_security_zone.test.id
          - model_name: type
            type: String
            description: Type of the interface object; either 'SecurityZone' or 'InterfaceGroup'.
            enum_values: [SecurityZone, InterfaceGroup]
            example: SecurityZone
            mandatory: true
            test_value: fmc_security_zone.test.type
          - model_name: name
            type: String
            description: Name of the interface object.
            example: Outside
            mandatory: true
            test_value: fmc_security_zone.test.name

test_prerequisites: |-
  resource "fmc_ftd_platform_settings" "test" {
    name        = "ftd_platform_settings_icmp_access"
  }

  resource "fmc_host" "test" {
    name = "ftd_platform_settings_icmp_access_host1"
    ip   = "10.0.2.1"
  }

  resource "fmc_security_zone" "test" {
    name           = "ftd_platform_settings_icmp_access_zone1"
    interface_type = "ROUTED"
  }

  resource "fmc_icmpv4_object" "test" {
    icmp_type   = 3
    code        = 0
    name        = "ftd_platform_settings_icmp_access_icmp1"
  }
