---
name: Hosts
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/object/hosts
doc_category: Objects
is_bulk: true
minimum_version_bulk_delete: "7.4"
attributes:
  - model_name: items
    type: Map
    description: >-
      Map of hosts. The key of the map is the name of the individual Host.
    map_key_example: hosts_1
    mandatory: true
    attributes:
      - model_name: id
        type: String
        resource_id: true
        description: Id of the managed Host.
        exclude_example: true
        exclude_test: true
      - model_name: description
        type: String
        description: Description of the resource.
        example: "My Host 1"
      - model_name: overridable
        type: Bool
        description: Indicates whether object values can be overridden.
        exclude_example: true
        example: "true"
      - model_name: value
        tf_name: ip
        type: String
        mandatory: true
        description: IP of the host.
        example: 10.1.1.1
      - model_name: type
        type: String
        description: Type of the object; this value is always 'Host'.
        computed: true
