---
name: VPN S2S IKE Settings
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/policy/ftds2svpns/%v/ikesettings
res_description: This resource manages FTD Site-to-Site (S2S) Virtual Private Networks (VPNs) IKEv1 and IKEv2 settings.
put_create: true
no_delete: true
doc_category: VPN
attributes:
  - tf_name: vpn_s2s_id
    type: String
    reference: true
    description: Id of the parent VPN S2S Topology.
    example: 76d24097-41c4-4558-a4d0-a8c07ac08470
    test_value: TBD
  - model_name: type
    type: String
    description: Type of the object; this value is always 'IkeSetting'.
    computed: true
  # IKEv1 settings
  - model_name: authenticationType
    data_path: [ikeV1Settings]
    tf_name: ikev1_authentication_type
    type: String
    description: The authentication type for IKEv1.
    enum_values: [MANUAL_PRE_SHARED_KEY, AUTOMATIC_PRE_SHARED_KEY, CERTIFICATE]
    example: MANUAL_PRE_SHARED_KEY
  - model_name: automaticPreSharedKeyLength
    data_path: [ikeV1Settings]
    tf_name: ikev1_automatic_pre_shared_key_length
    type: Int64
    description: The length of the automatically generated pre-shared key for IKEv1.
    min_int: 1
    max_int: 127
    exclude_example: true
  - model_name: manualPreSharedKey
    data_path: [ikeV1Settings]
    tf_name: ikev1_manual_pre_shared_key
    type: String
    description: The manually configured pre-shared key for IKEv1.
    example: my_pre_shared_key123
    write_only: true
  # model_name certificateAuthen
  - model_name: policies
    data_path: [ikeV1Settings]
    tf_name: ikev1_policies
    type: Set
    description: Set of policies for IKEv1 settings.
    attributes:
      - model_name: id
        type: String
        description: Id of the IKEv1 policy
        id: true
        example: 76d24097-41c4-4558-a4d0-a8c07ac08470
        test_value: TBD
        mandatory: true
      - model_name: name
        type: String
        description: Name of the IKEv1 policy
        example: my_ikev1_policy
        mandatory: true
  # IKEv2 settings
  - model_name: authenticationType
    data_path: [ikeV2Settings]
    tf_name: ikev2_authentication_type
    type: String
    description: The authentication type for IKEv2.
    enum_values: [MANUAL_PRE_SHARED_KEY, AUTOMATIC_PRE_SHARED_KEY, CERTIFICATE]
    example: MANUAL_PRE_SHARED_KEY
  - model_name: automaticPreSharedKeyLength
    data_path: [ikeV2Settings]
    tf_name: ikev2_automatic_pre_shared_key_length
    type: Int64
    description: The length of the automatically generated pre-shared key for IKEv2.
    min_int: 1
    max_int: 127
    exclude_example: true
  - model_name: manualPreSharedKey
    data_path: [ikeV2Settings]
    tf_name: ikev2_manual_pre_shared_key
    type: String
    description: The manually configured pre-shared key for IKEv2.
    example: my_pre_shared_key123
    write_only: true
  - model_name: enforceHexBasedPreSharedKeyOnly
    data_path: [ikeV2Settings]
    tf_name: ikev2_enforce_hex_based_pre_shared_key_only
    type: Bool
    description: Indicates whether to enforce the use of a hex-based pre-shared key for IKEv2.
    example: "false"
  # model_name certificateAuthen
  - model_name: policies
    data_path: [ikeV2Settings]
    tf_name: ikev2_policies
    type: Set
    description: Set of policies for IKEv2 settings.
    attributes:
      - model_name: id
        type: String
        description: Id of the IKEv2 policy
        id: true
        example: 76d24097-41c4-4558-a4d0-a8c07ac08470
        test_value: TBD
        mandatory: true
      - model_name: name
        type: String
        description: Name of the IKEv2 policy
        example: my_ikev2_policy
        mandatory: true