// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"

	"github.com/CiscoDevNet/terraform-provider-fmc/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-fmc"
	"github.com/tidwall/gjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &DeviceCertificateDataSource{}
	_ datasource.DataSourceWithConfigure = &DeviceCertificateDataSource{}
)

func NewDeviceCertificateDataSource() datasource.DataSource {
	return &DeviceCertificateDataSource{}
}

type DeviceCertificateDataSource struct {
	client *fmc.Client
}

func (d *DeviceCertificateDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_certificate"
}

func (d *DeviceCertificateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewAttributeDescription("This data source reads the Device Certificate.").AddMinimumVersionHeaderDescription().AddMinimumVersionDescription("7.7").String,

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Id of the object",
				Optional:            true,
				Computed:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "Name of the FMC domain",
				Optional:            true,
			},
			"device_id": schema.StringAttribute{
				MarkdownDescription: "Id of the device the certificate is enrolled on.",
				Optional:            true,
				Computed:            true,
			},
			"certificate_enrollment_id": schema.StringAttribute{
				MarkdownDescription: "Id of the certificate enrollment object to enroll on the device.",
				Optional:            true,
				Computed:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Type of the object; this value is always 'DeviceCertificate'.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the device certificate (derived from the certificate enrollment).",
				Computed:            true,
			},
		},
	}
}
func (d *DeviceCertificateDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.ExactlyOneOf(
			path.MatchRoot("id"),
			path.MatchRoot("device_id"),
			path.MatchRoot("certificate_enrollment_id"),
		),
	}
}

func (d *DeviceCertificateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.client = req.ProviderData.(*FmcProviderData).Client
}

// End of section. //template:end model

// Section below was generated by "gen/generator.go" and hand-wired for the /devices/certificates list endpoint.
// The Device Certificate has no per-object GET; it is read from a list endpoint that can be filtered by device id.
// Exactly one of `id`, `device_id` or `certificate_enrollment_id` is set (enforced by ConfigValidators).

func (d *DeviceCertificateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {

	// Check if FMC client is connected to supports this object
	if d.client.FMCVersionParsed.LessThan(minFMCVersionDeviceCertificate) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("UnsupportedVersion: FMC version %s does not support Device Certificate, minimum required version is 7.4", d.client.FMCVersion))
		return
	}
	var config DeviceCertificate

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !config.Domain.IsNull() && config.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(config.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.Id.String()))

	// When querying by device_id, filter server-side; otherwise list all and match client-side.
	urlPath := config.getPath() + "?expanded=true"
	if !config.DeviceId.IsNull() && config.DeviceId.ValueString() != "" {
		urlPath = config.getPath() + "?filter=deviceId:" + url.QueryEscape(config.DeviceId.ValueString()) + "&expanded=true"
	}
	res, err := d.client.Get(urlPath, reqMods...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve objects, got error: %s", err))
		return
	}

	// Locate the requested item.
	var item gjson.Result
	switch {
	case !config.Id.IsNull() && config.Id.ValueString() != "":
		res.Get("items").ForEach(func(_, v gjson.Result) bool {
			if v.Get("id").String() == config.Id.ValueString() {
				item = v
				return false
			}
			return true
		})
	case !config.CertificateEnrollmentId.IsNull() && config.CertificateEnrollmentId.ValueString() != "":
		item = deviceCertificateFindByEnrollment(res, config.CertificateEnrollmentId.ValueString())
	default: // queried by device_id
		items := res.Get("items").Array()
		if len(items) > 1 {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Multiple certificates enrolled on device_id %q; query by certificate_enrollment_id or id instead.", config.DeviceId.ValueString()))
			return
		}
		if len(items) == 1 {
			item = items[0]
		}
	}
	if !item.Exists() {
		resp.Diagnostics.AddError("Client Error", "Failed to find a matching Device Certificate for the provided query.")
		return
	}

	// device_id and certificate_enrollment_id are query inputs that are not returned at the item root, so preserve them.
	deviceId := config.DeviceId
	certEnrollmentId := config.CertificateEnrollmentId

	config.Id = types.StringValue(item.Get("id").String())
	config.fromBody(ctx, item)

	config.DeviceId = deviceId
	config.CertificateEnrollmentId = certEnrollmentId

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.Id.ValueString()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
