// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-fmc/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-fmc"
	"github.com/tidwall/gjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &DistinguishedNamesDataSource{}
	_ datasource.DataSourceWithConfigure = &DistinguishedNamesDataSource{}
)

func NewDistinguishedNamesDataSource() datasource.DataSource {
	return &DistinguishedNamesDataSource{}
}

type DistinguishedNamesDataSource struct {
	client *fmc.Client
}

func (d *DistinguishedNamesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_distinguished_names"
}

func (d *DistinguishedNamesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewAttributeDescription("This data source reads the Distinguished Names.").AddMinimumVersionHeaderDescription().AddMinimumVersionDescription("7.4").String,

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Id of the object",
				Computed:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "Name of the FMC domain",
				Optional:            true,
			},
			"items": schema.MapNestedAttribute{
				MarkdownDescription: "Map of Distinguished Names. The key of the map is the name of the individual Distinguished Name.",
				Optional:            true,
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Id of the Distinguished Name object.",
							Computed:            true,
						},
						"type": schema.StringAttribute{
							MarkdownDescription: "Type of the object; this value is always 'DistinguishedName'.",
							Computed:            true,
						},
						"distinguished_name": schema.StringAttribute{
							MarkdownDescription: "The value of the distinguished name, provided as comma-separated attribute-value pairs (for example `CN=example.com,OU=IT,O=Example,C=US`).",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *DistinguishedNamesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.client = req.ProviderData.(*FmcProviderData).Client
}

// End of section. //template:end model

// Section that was generated by "gen/generator.go" but is now hand-owned (template markers
// removed) so that the per-item distinguished-name normalization after fromBody survives regeneration.

func (d *DistinguishedNamesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DistinguishedNames

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Preserve any configured distinguished name of each item so we can reconcile it with
	// the (re-ordered, slash-separated) value returned by FMC after fromBody overwrites it.
	priorDistinguishedNames := make(map[string]string, len(config.Items))
	for k, v := range config.Items {
		priorDistinguishedNames[k] = v.DistinguishedName.ValueString()
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !config.Domain.IsNull() && config.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(config.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.Id.String()))

	// Get all objects from FMC
	urlPath := config.getPath() + "?expanded=true"
	res, err := d.client.Get(urlPath, reqMods...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
		return
	}

	// Read all items if user did not provide any specific item names in the config
	if len(config.Items) == 0 {
		if config.Items == nil {
			config.Items = map[string]DistinguishedNamesItems{}
		}
		res.Get("items").ForEach(func(_, v gjson.Result) bool {
			if name := v.Get("name").String(); name != "" {
				config.Items[name] = DistinguishedNamesItems{}
			}
			return true
		})
	}

	config.fromBody(ctx, res)

	// FMC returns each distinguished name slash-separated and in a canonicalized attribute
	// order. Normalize it back to the comma-separated form and preserve the user's original
	// ordering when the two values describe the same set of components.
	for k, item := range config.Items {
		if !item.DistinguishedName.IsNull() {
			item.DistinguishedName = types.StringValue(reconcileDistinguishedName(priorDistinguishedNames[k], item.DistinguishedName.ValueString()))
			config.Items[k] = item
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.Id.ValueString()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
