// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

package provider

// The CRUD functions below were generated by "gen/generator.go" and then hand-wired for the Device
// Certificate resource, which spans multiple FMC endpoints (see the definition YAML header for details).
// The autogeneration markers were intentionally removed from these sections so `go generate` does not
// overwrite the manual wiring. The model file (toBody/fromBody/... and struct) remains fully generated,
// and the shared manual helpers live in model_fmc_device_certificate.go.
import (
	"context"
	"fmt"
	"net/url"
	"strings"

	"github.com/CiscoDevNet/terraform-provider-fmc/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-fmc"
	"github.com/tidwall/gjson"
)

// Section below is generated&owned by "gen/generator.go". //template:begin model

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource = &DeviceCertificateResource{}
)

func NewDeviceCertificateResource() resource.Resource {
	return &DeviceCertificateResource{}
}

type DeviceCertificateResource struct {
	client *fmc.Client
}

func (r *DeviceCertificateResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_certificate"
}

func (r *DeviceCertificateResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: helpers.NewAttributeDescription("This resource manages a Device Certificate - the enrollment of a certificate (via a certificate enrollment object) onto a device.").AddMinimumVersionHeaderDescription().AddMinimumVersionDescription("7.4").String,

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Id of the object",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "Name of the FMC domain",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"device_id": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Id of the device the certificate is enrolled on.").String,
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"certificate_enrollment_id": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Id of the certificate enrollment object to enroll on the device.").String,
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Type of the object; this value is always 'DeviceCertificate'.").String,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Name of the device certificate (derived from the certificate enrollment).").String,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *DeviceCertificateResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*FmcProviderData).Client
}

// End of section. //template:end model

// Section below was generated by "gen/generator.go" and hand-wired for the managecertificates endpoint.

func (r *DeviceCertificateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {

	// Check if FMC client is connected to supports this object
	if r.client.FMCVersionParsed.LessThan(minFMCVersionDeviceCertificate) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("UnsupportedVersion: FMC version %s does not support Device Certificate creation, minumum required version is 7.4", r.client.FMCVersion))
		return
	}
	var plan DeviceCertificate

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
		return
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !plan.Domain.IsNull() && plan.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(plan.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.DeviceId.ValueString()))

	// Enroll the certificate onto the device via the operational endpoint (async task).
	body := deviceCertificateManageBody("ENROLL", plan.DeviceId.ValueString(), plan.CertificateEnrollmentId.ValueString())
	res, err := r.client.Post(deviceCertificateManagePath, body, reqMods...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to enroll certificate (POST), got error: %s, %s", err, res.String()))
		return
	}

	// Wait for the enrollment task to finish.
	taskID := res.Get("metadata.task.id").String()
	if taskID != "" {
		tflog.Debug(ctx, fmt.Sprintf("%s: Async enrollment task initiated (id: %s)", plan.DeviceId.ValueString(), taskID))
		diags = FMCWaitForJobToFinish(ctx, r.client, taskID, reqMods)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}
	}

	// The device certificate id is known only after enrollment; read it back from the list endpoint.
	bulk, err := r.client.Get(plan.getPath()+"?filter=deviceId:"+url.QueryEscape(plan.DeviceId.ValueString())+"&expanded=true", reqMods...)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to read enrolled certificate (GET), got error: %s, %s", err, bulk.String()))
		return
	}
	item := deviceCertificateFindByEnrollment(bulk, plan.CertificateEnrollmentId.ValueString())
	if !item.Exists() {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Certificate enrollment %q not found on device %q after enrollment: %s", plan.CertificateEnrollmentId.ValueString(), plan.DeviceId.ValueString(), bulk.String()))
		return
	}

	plan.Id = types.StringValue(item.Get("id").String())
	plan.fromBodyUnknowns(ctx, item)

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// Section below was generated by "gen/generator.go" and hand-wired for the /devices/certificates list endpoint.

func (r *DeviceCertificateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Check if FMC client is connected to supports this object
	if r.client.FMCVersionParsed.LessThan(minFMCVersionDeviceCertificate) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("UnsupportedVersion: FMC version %s does not support Device Certificate, minimum required version is 7.4", r.client.FMCVersion))
		return
	}
	var state DeviceCertificate

	// Read state
	diags := req.State.Get(ctx, &state)
	if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
		return
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !state.Domain.IsNull() && state.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(state.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.String()))

	// Device certificates are read from a list endpoint filtered by device id (no per-object GET).
	res, err := r.client.Get(state.getPath()+"?filter=deviceId:"+url.QueryEscape(state.DeviceId.ValueString())+"&expanded=true", reqMods...)
	if err != nil && strings.Contains(err.Error(), "StatusCode 404") {
		resp.State.RemoveResource(ctx)
		return
	} else if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object (GET), got error: %s, %s", err, res.String()))
		return
	}

	// Locate this resource's item. Prefer the id captured at create; fall back to the enrollment reference.
	var item gjson.Result
	res.Get("items").ForEach(func(_, i gjson.Result) bool {
		if i.Get("id").String() == state.Id.ValueString() {
			item = i
			return false
		}
		return true
	})
	if !item.Exists() {
		item = deviceCertificateFindByEnrollment(res, state.CertificateEnrollmentId.ValueString())
	}
	if !item.Exists() {
		// The certificate is no longer enrolled on the device.
		resp.State.RemoveResource(ctx)
		return
	}

	imp, diags := helpers.IsFlagImporting(ctx, req)
	if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
		return
	}

	// The list item is the DeviceCertificateModel. certificate_enrollment_id and device_id are RequiresReplace
	// inputs that are not returned at the item root, so preserve them across the partial/full read.
	certEnrollmentId := state.CertificateEnrollmentId
	deviceId := state.DeviceId

	// After `terraform import` we switch to a full read.
	if imp {
		state.fromBody(ctx, item)
	} else {
		state.fromBodyPartial(ctx, item)
	}

	state.CertificateEnrollmentId = certEnrollmentId
	state.DeviceId = deviceId

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)

	helpers.SetFlagImporting(ctx, false, resp.Private, &resp.Diagnostics)
}

// Section below was generated by "gen/generator.go" and hand-wired.
// All configurable attributes (device_id, certificate_enrollment_id) are RequiresReplace, so a change always
// triggers Delete+Create rather than Update. This Update therefore only persists the (unchanged) plan to state.

func (r *DeviceCertificateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DeviceCertificate

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update is a no-op (all inputs are RequiresReplace)", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

// Section below was generated by "gen/generator.go" and hand-wired for the managecertificates endpoint.

func (r *DeviceCertificateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DeviceCertificate

	// Read state
	diags := req.State.Get(ctx, &state)
	if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
		return
	}

	// Set request domain if provided
	reqMods := [](func(*fmc.Req)){}
	if !state.Domain.IsNull() && state.Domain.ValueString() != "" {
		reqMods = append(reqMods, fmc.DomainName(state.Domain.ValueString()))
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))

	// Remove the certificate from the device via the operational endpoint (async task).
	body := deviceCertificateManageBody("DELETE", state.DeviceId.ValueString(), state.CertificateEnrollmentId.ValueString())
	res, err := r.client.Post(deviceCertificateManagePath, body, reqMods...)
	if err != nil && !strings.Contains(err.Error(), "StatusCode 404") {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete certificate (POST), got error: %s, %s", err, res.String()))
		return
	}

	taskID := res.Get("metadata.task.id").String()
	if taskID != "" {
		tflog.Debug(ctx, fmt.Sprintf("%s: Async delete task initiated (id: %s)", state.Id.ValueString(), taskID))
		diags = FMCWaitForJobToFinish(ctx, r.client, taskID, reqMods)
		if resp.Diagnostics.Append(diags...); resp.Diagnostics.HasError() {
			return
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

// Section below is generated&owned by "gen/generator.go". //template:begin import
// End of section. //template:end import

// Section below is generated&owned by "gen/generator.go". //template:begin createSubresources

// End of section. //template:end createSubresources

// Section below is generated&owned by "gen/generator.go". //template:begin deleteSubresources

// End of section. //template:end deleteSubresources

// Section below is generated&owned by "gen/generator.go". //template:begin updateSubresources

// End of section. //template:end updateSubresources
